name: passing
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  passing-values-bw-steps:
     runs-on: ubuntu-latest
     steps:
     - name: set the value using env vars
       run: |
          echo "variablename=this-is -value" >> $GITHUB_ENV
    
     - name: get-variable-value
       run: |
        echo: "imprimir valores"
        echo: variablename: {{ env.variablename }}
     
    
          
